<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	<PackageId>PaleyExpressions</PackageId>
	<Version>0.0.13-local</Version> <!-- 06/09/26-->
	<Authors>Jonathan Palethorpe</Authors>
	<Description>An expression evaluator</Description>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
